import requests

# The URL of the FastAPI app running locally
url = "http://localhost:8000/get-user-namespaces"

# Simulate a session with a fake token by adding it to the cookies
cookies = {
    "session": "eyJzdGF0ZSI6ICIxNzg4Zjk3NS1iZWUwLTQxODEtOGE2YS03MTM0OTBmODM0Y2MiLCAidXNlciI6IHsic3ViIjogImF1dGgwfDY3ZTExZTNjY2VkNjhkNDMyNzI1YTFmYyIsICJuaWNrbmFtZSI6ICJuaWdnYSIsICJuYW1lIjogIm5pZ2dhQGdtYWlsLmNvbSIsICJwaWN0dXJlIjogImh0dHBzOi8vcy5ncmF2YXRhci5jb20vYXZhdGFyLzgxMzQwN2NhYmEwZDQ4ZDNhNzgwNzcwODFhNTM1ZjhmP3M9NDgwJnI9cGcmZD1odHRwcyUzQSUyRiUyRmNkbi5hdXRoMC5jb20lMkZhdmF0YXJzJTJGbmkucG5nIiwgInVwZGF0ZWRfYXQiOiAiMjAyNS0wMy0yNVQyMjoxMzo1NS43MzlaIiwgImVtYWlsIjogIm5pZ2dhQGdtYWlsLmNvbSIsICJlbWFpbF92ZXJpZmllZCI6IGZhbHNlfSwgInRva2VuIjogeyJhY2Nlc3NfdG9rZW4iOiAiZXlKaGJHY2lPaUprYVhJaUxDSmxibU1pT2lKQk1qVTJSME5OSWl3aWFYTnpJam9pYUhSMGNITTZMeTlrWlhZdGFuZHlOSHBrYnpKeVptZ3dabkJvTkM1MWN5NWhkWFJvTUM1amIyMHZJbjAuLlVLWHJ6X2tCUzNkOUtUMnUuZl82NTBuWmRrS09OU0xVdldLVkdJNllkOWVfLXNweHoxQ3Q1bEo5WmVVV0tBVjgxOWhLX240UDhDS21CYzh0LXlQbnhYYWNpWWVCU1N1ZHNaeGZON3NOWXFQUkV5dDZYTTBjc1hzVDRhdGpaWF9FRXp5bkhfb29DWHNjMVVkNHRkTzBXNElMclFTMTJ3YUdGUWs3NFZLTWhleHFxY1dMNUhsVFQ1VmdmUEhkQm02eVVFT3JGT0FJekhJYVJNTDNJS0JLNHBHRXlPX2NQUG13X20xNi1yZGx..."
}

# Send the GET request with the fake session token
response = requests.get(url, cookies=cookies)

# Print the status code and response
print("Status Code:", response.status_code)
print("Response Body:", response.json())
